package main

import("encoding/json";"flag";"fmt";"net";"net/http";"os/exec";"runtime";"strings";"sync";"time";"github.com/gorilla/websocket";"github.com/shirou/gopsutil/v4/cpu";"github.com/shirou/gopsutil/v4/disk";"github.com/shirou/gopsutil/v4/load";"github.com/shirou/gopsutil/v4/mem";gnet "github.com/shirou/gopsutil/v4/net")
type Metric struct{At time.Time `json:"at"`;CPU,Memory,Disk,Load1 float64;RxBPS,TxBPS,RxTotal,TxTotal uint64;IPv4 string}
func main(){server:=flag.String("server","","panel URL");token:=flag.String("token","","token");flag.Parse();url:=strings.Replace(strings.TrimRight(*server,"/"),"https://","wss://",1);url=strings.Replace(url,"http://","ws://",1)+"/agent/ws?token="+*token;for{c,_,e:=websocket.DefaultDialer.Dial(url,nil);if e!=nil{time.Sleep(5*time.Second);continue};run(c);c.Close();time.Sleep(3*time.Second)}}
func run(c *websocket.Conn){var ping,cmd string;go func(){for{var x map[string]any;if c.ReadJSON(&x)!=nil{return};if x["type"]=="config"{ping,_=x["pingTarget"].(string);cmd,_=x["changeIpCommand"].(string)};if x["type"]=="action"{a,_:=x["action"].(string);if a=="changeip"{shell(cmd)};if a=="reboot"{shell("reboot")};if a=="ping"{go monitor(c,ping,cmd,true)}}}}();var prx,ptx uint64;t:=time.NewTicker(time.Second);defer t.Stop();for range t.C{io,_:=gnet.IOCounters(false);if len(io)==0{continue};rx,tx:=io[0].BytesRecv,io[0].BytesSent;m:=memInfo(rx,tx,prx,ptx);prx,ptx=rx,tx;if c.WriteJSON(map[string]any{"type":"metric","metric":m})!=nil{return}}}
func memInfo(rx,tx,prx,ptx uint64)*Metric{m,_:=mem.VirtualMemory();d,_:=disk.Usage("/");l,_:=load.Avg();cp,_:=cpu.Percent(0,false);v:=&Metric{At:time.Now(),Memory:m.UsedPercent,Disk:d.UsedPercent,RxTotal:rx,TxTotal:tx,IPv4:publicIP()};if len(cp)>0{v.CPU=cp[0]};if l!=nil{v.Load1=l.Load1};if rx>=prx{v.RxBPS=rx-prx};if tx>=ptx{v.TxBPS=tx-ptx};return v}
var ipCache struct{sync.Mutex;value string;at time.Time}
func publicIP()string{ipCache.Lock();defer ipCache.Unlock();if ipCache.value!=""&&time.Since(ipCache.at)<30*time.Second{return ipCache.value};cl:=http.Client{Timeout:3*time.Second};r,e:=cl.Get("https://api.ipify.org");if e!=nil{return ipCache.value};defer r.Body.Close();var s string;fmt.Fscan(r.Body,&s);if s!=""{ipCache.value=s;ipCache.at=time.Now()};return ipCache.value}
func monitor(c *websocket.Conn,target,cmd string,once bool){if target==""{return};fails:=0;for{timeout:=5*time.Minute;if !reachable(target){fails++;timeout=2*time.Minute}else{fails=0};if fails>=3{shell(cmd);c.WriteJSON(map[string]any{"type":"event","event":"change_ip","detail":"连续三次连通性失败，已执行换 IP 命令"});fails=0};if once{return};time.Sleep(timeout)}}
func reachable(target string)bool{host:=target;if h,_,e:=net.SplitHostPort(target);e==nil{host=h};arg:="-c";if runtime.GOOS=="windows"{arg="-n"};return exec.Command("ping",arg,"1",host).Run()==nil}
func shell(s string){if s==""{return};exec.Command("/bin/sh","-c",s).Run()}
var _=json.Marshal
