let data=[];const $=id=>document.getElementById(id),gb=n=>n?`${(n/1073741824).toFixed(2)} GB`:'0 GB',speed=n=>n>1048576?`${(n/1048576).toFixed(2)} MB/s`:`${(n/1024).toFixed(1)} KB/s`;
async function api(url,opt={}){let r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});if(r.status===401)throw Error('auth');if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function login(e){e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('password').value})});start()}catch{$('loginError').textContent='密码错误'}}
async function start(){try{data=await api('/api/vps');$('login').hidden=true;$('app').hidden=false;render();connect()}catch(e){if(e.message!=='auth')alert(e.message)}}
function render(){let on=data.filter(v=>v.online).length;$('online').textContent=`${on} / ${data.length} 在线`;$('cards').innerHTML=data.map(v=>`<article class="card"><div class="cardhead"><div><span class="dot ${v.online?'on':''}"></span><b>${esc(v.name)}</b></div><span class="ip">${v.IPv4||v.ipv4||'等待 IP'}</span></div><div class="traffic"><div><small>↓ 下载</small><div class="speed down">${speed(v.RxBPS||0)}</div></div><div><small>↑ 上传</small><div class="speed up">${speed(v.TxBPS||0)}</div></div></div><div class="stats">${stat('CPU',v.CPU)}${stat('内存',v.Memory)}${stat('磁盘',v.Disk)}${stat('负载',v.Load1,false)}</div><div class="usage">今日 ${gb(v.dayBytes)} / ${v.dayLimit?gb(v.dayLimit):'无限'}　·　本月 ${gb(v.monthBytes)} / ${v.monthLimit?gb(v.monthLimit):'无限'}<br>永久累计 ${gb(v.totalBytes)}</div><div class="actions"><button class="ghost" onclick="edit('${v.id}')">设置</button><button class="ghost" onclick="act('${v.id}','ping')">立即 Ping</button><button class="ghost" onclick="act('${v.id}','changeip')">换 IP</button><button class="ghost" onclick="act('${v.id}','dns')">更新 DNS</button><button class="ghost" onclick="confirm('确认重启？')&&act('${v.id}','reboot')">重启</button></div></article>`).join('')||'<p>还没有 VPS，点击右上角添加。</p>'}
function stat(n,v,pc=true){return `<div><small>${n}</small><b>${(+v||0).toFixed(1)}${pc?'%':''}</b><span class="bar"><i style="width:${Math.min(+v||0,100)}%"></i></span></div>`}function esc(s){return(s||'').replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}
function connect(){let ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/live`);ws.onmessage=e=>{let x=JSON.parse(e.data),v=data.find(v=>v.id===x.vpsId);if(v&&x.metric){Object.assign(v,x.metric,{online:true});render()}};ws.onclose=()=>setTimeout(connect,2000)}
function openAdd(){$('formTitle').textContent='添加 VPS';$('editor').querySelector('form').reset();$('id').value='';$('install').textContent='';$('editor').showModal()}function edit(id){let v=data.find(x=>x.id===id);$('formTitle').textContent='编辑 '+v.name;for(let k of ['id','name','billingDay','pingTarget','changeIpCommand','cfZoneId','cfRecordId','cfRecordName'])$(k).value=v[k]||'';$('dayLimit').value=(v.dayLimit||0)/1073741824;$('monthLimit').value=(v.monthLimit||0)/1073741824;$('editor').showModal()}
async function save(e){e.preventDefault();let id=$('id').value,v={name:$('name').value,billingDay:+$('billingDay').value,dayLimit:+$('dayLimit').value*1073741824,monthLimit:+$('monthLimit').value*1073741824,pingTarget:$('pingTarget').value,changeIpCommand:$('changeIpCommand').value,cfZoneId:$('cfZoneId').value,cfRecordId:$('cfRecordId').value,cfRecordName:$('cfRecordName').value,cfToken:$('cfToken').value};try{if(id)await api('/api/vps/'+id,{method:'PUT',body:JSON.stringify(v)});else{let x=await api('/api/vps',{method:'POST',body:JSON.stringify(v)});$('install').textContent='安装命令：\n'+x.install;data=await api('/api/vps');render();return}data=await api('/api/vps');render();$('editor').close()}catch(x){alert(x.message)}}async function act(id,a){try{await api(`/api/vps/${id}/${a}`,{method:'POST'});alert('指令已发送')}catch(e){alert(e.message)}}
setInterval(()=>$('clock').textContent=new Date().toLocaleString('zh-CN',{hour12:false}),1000);start();

// Agent 仍按 100ms 采样；界面最多每 250ms 重绘一次，减少数字抖动和浏览器负载。
const drawNow=render;let drawTimer=0;render=function(){if(drawTimer)return;drawTimer=setTimeout(()=>{drawTimer=0;drawNow()},500)};
